<a href="https://colab.research.google.com/github/endzix22/machine-learning-bootcamp/blob/main/02_gradient_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px 

np.random.seed(42)

Wygenerowanie danych

In [13]:
X1 = np.array([1, 2, 3, 4, 5, 6])
Y = np.array([3000, 3250, 3500, 3750, 4000, 4250])
m = len(X1)

print(f'Lata pracy: {X1}')
print(f'Wynagrodzenie: {Y}')
print(f'Liczba próbek: {m}')

Lata pracy: [1 2 3 4 5 6]
Wynagrodzenie: [3000 3250 3500 3750 4000 4250]
Liczba próbek: 6


Przygotowanie danych

In [14]:
X1 = X1.reshape(m, 1)
Y = Y.reshape(-1, 1)
print(X1)
print(X1.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [15]:
bias = np.ones((m, 1))
print(bias)
print(bias.shape)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(6, 1)


In [16]:
#ta macierz x (obczaj zeszyt), dodaje sie bias ten ala wektor w macierzy 

In [17]:
X = np.append(bias, X1, axis=1)
print(X)
print(X.shape)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
(6, 2)


Losowa inicjalizacja parametrow

In [18]:
eta=0.01
#wskaznik uczenia, o tyle bedzie te dalsze kroki wykonywac
weights=np.random.randn(2,1) #losowa inicjalizacja wag 
#zobacz te wagi na koncu dwie ostatnie 
print(X)
print(weights)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
[[-0.46947439]
 [ 0.54256004]]


Metoda gradientu prostego

In [19]:
intercept=[]
coef=[]
#bedziemy dodawac wartosci wo i w1 (czyli a i b)


for i in range(3000):
    gradient = (2 / m) * X.T.dot(X.dot(weights) - Y) #wzor na gradient
    weights = weights - eta * gradient 
    #nasze wagi aktualizujemy, w naszym kroku bedziemy odejmowac oblicozny gradient razy
    #wskaznik uczenia, co stanowi nowe wagi:
    
    intercept.append(weights[0][0])
    coef.append(weights[1][0])

print(weights)

[[2749.95599051]
 [ 250.01027971]]


In [20]:
#2749.95599051->wo
#250.01027971->w1
#zatrzymalnie algorytmu po 3000 krokow. 


In [22]:
df=pd.DataFrame(data={'intercept':intercept,'coef':coef})
df.head()
#utworzenie dataframe z naszych tablic 

intercept        coef
0   72.001936  268.744180
1  124.249805  450.518310
2  162.728527  573.496936
3  191.829171  656.478535
4  214.539090  712.252004

Wizualizacja dopasowania

In [25]:
px.line(df, y='intercept', width=800, title='Dopasowanie: intercept')
#wykres dla b  wo

In [26]:
px.line(df, y='coef', width=800, title='Dopasowanie: coef')
#wykres dla a w1