<a href="https://colab.research.google.com/github/endzix22/machine-learning-bootcamp/blob/main/funkcja_aktywacji.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import plotly.express as px
import math

np.set_printoptions(precision=6)

#### <a name='a2'></a> 1.2 ReLU Function - Rectified Linear Unit
####     $$f(x) = max(x, 0)$$


In [2]:
#funkcja aktywacji relu, 
#zwracamy maksimum z wart jaka przekazalismy
def max_relu(x):
  return max(x,0,0)


In [3]:
for i in [-10., -5., 0., 5., 10.]:
    print(max_relu(i))

0
0
0.0
5.0
10.0


In [4]:
#zainicjujmy randomowe wartosci i je posortujmy
data = np.random.randn(50)
data = sorted(data)
data

[-1.6421040601215573,
 -1.3687727591084677,
 -1.1942688530053414,
 -1.1839803197481027,
 -0.9291212060956882,
 -0.8349752807992086,
 -0.8135600917655734,
 -0.527151322996668,
 -0.43898398244014175,
 -0.3936419167776829,
 -0.33726631866121876,
 -0.3050689192217199,
 -0.28984422664103754,
 -0.2706826664656796,
 -0.2604225157954868,
 -0.2594638452474605,
 -0.25656803597316735,
 -0.17746004241540583,
 -0.15407203740567194,
 -0.05911210445948866,
 0.11872082631838429,
 0.14585246837385493,
 0.22003179860396194,
 0.2835390028483133,
 0.32659091362779025,
 0.4119573725490942,
 0.42458083689608056,
 0.4528530464677943,
 0.6286186723876884,
 0.6657538873116698,
 0.7505219101577106,
 0.776691278787996,
 0.7767999025237786,
 0.8991955757213047,
 0.9560211524767179,
 0.965679938260422,
 0.9894096669594803,
 1.0074124540244078,
 1.0267180315723627,
 1.0948118739507207,
 1.2366938657734183,
 1.3319636178259575,
 1.3604985687355768,
 1.700782251198892,
 1.7029739491350768,
 1.7151279502876582,
 1.749

In [5]:
# wygenerowanie danych do wykresu
max_relu_data = np.array([max_relu(x) for x in data])
max_relu_data

array([0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.118721, 0.145852, 0.220032, 0.283539,
       0.326591, 0.411957, 0.424581, 0.452853, 0.628619, 0.665754,
       0.750522, 0.776691, 0.7768  , 0.899196, 0.956021, 0.96568 ,
       0.98941 , 1.007412, 1.026718, 1.094812, 1.236694, 1.331964,
       1.360499, 1.700782, 1.702974, 1.715128, 1.74955 , 1.859771,
       2.221024, 2.495267])

In [6]:
#teraz utworzmy DF by moc pokazac dane przy pomocy plotly 
df=pd.DataFrame({'data':data,'max_relu_data':max_relu_data})
df.head()

data  max_relu_data
0 -1.642104            0.0
1 -1.368773            0.0
2 -1.194269            0.0
3 -1.183980            0.0
4 -0.929121            0.0

In [7]:
px.line(df,x='data',y='max_relu_data',width=700,height=400,title='ReLu Function')

#### <a name='a3'></a> 1.3 Funkcja Sigmoid
####    $$f(x) = \frac{1}{1 + e^{-x}}$$

In [8]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [9]:
data = 3 * np.random.randn(50)
data = sorted(data)
data

[-6.786321405133922,
 -6.186290816554129,
 -3.647309229744366,
 -3.2968860060259066,
 -3.1524799960927536,
 -3.1232300189751014,
 -3.0250712633541514,
 -2.930756166052646,
 -2.4552363585898367,
 -2.03704000987645,
 -1.8226652521822866,
 -1.3509936548100865,
 -1.2236323350686238,
 -0.8556889080865702,
 -0.8381225019696302,
 -0.7509166683887356,
 -0.46243988164117,
 -0.44694666963421903,
 -0.31533615420530947,
 -0.1557250823687132,
 0.0793282769987062,
 0.09982104422090242,
 0.36602147999924983,
 0.5118222243211346,
 0.5901363677744726,
 0.8172386086799727,
 0.9809464389751215,
 1.0535686907023885,
 1.2087812775620874,
 1.2669590152365762,
 1.3738414084459925,
 1.4438378715078088,
 1.4947672322199996,
 1.6140757348727952,
 1.8378748781007017,
 1.8715069397759625,
 1.9116255679298526,
 2.0500500000920354,
 2.140000515958236,
 2.8732092221991175,
 3.1958572268487053,
 3.4512458445159737,
 3.6065221052925667,
 3.6969047988851225,
 3.7513036562482314,
 4.019070070551655,
 4.604195743708582,


In [10]:
sigmoid_data = [sigmoid(x) for x in sorted(data)]
sigmoid_data

[0.0011278412373267755,
 0.002053219670383422,
 0.02539922584448086,
 0.03567817221083002,
 0.04099367058394032,
 0.042159144956597464,
 0.04630600263183529,
 0.0506539499640767,
 0.07905646670607316,
 0.11536848071408025,
 0.13911437107081032,
 0.20570796887780896,
 0.2272978588465495,
 0.2982408425397625,
 0.3019303540631976,
 0.32062159618672326,
 0.3864071759605824,
 0.3900869674626287,
 0.4218127814020295,
 0.4611472136733584,
 0.5198216755631383,
 0.5249345599960057,
 0.5904972790704874,
 0.6252335491413811,
 0.6433964341823529,
 0.6936498591817373,
 0.7272959701505408,
 0.741459596696374,
 0.7700832391208234,
 0.78022173706462,
 0.798000081951613,
 0.8090482643717227,
 0.8167927301280327,
 0.8339764799193441,
 0.8626971790949789,
 0.8666325466832304,
 0.8712016618271655,
 0.8859526708537948,
 0.8947306590744231,
 0.9465060714172294,
 0.9606780793422568,
 0.9692682726764704,
 0.9735713407349,
 0.9757999949150256,
 0.9770518782113131,
 0.9823475411247194,
 0.9900894529184179,
 0.9

In [11]:
df = pd.DataFrame({'data': data, 'sigmoid_data': sigmoid_data})
df.head()

data  sigmoid_data
0 -6.786321      0.001128
1 -6.186291      0.002053
2 -3.647309      0.025399
3 -3.296886      0.035678
4 -3.152480      0.040994

In [12]:
px.line(df, x='data', y='sigmoid_data', width=700, height=400, title='Sigmoid Function')

#### <a name='a4'></a> 1.4 Tanh Function

####   $$tanh (x) = \frac{e^{x} - e^{-x}}{e^{x} + e^{-x}}$$

In [13]:
def tanh(x):
    return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

In [14]:
data = 2 * np.random.randn(100)
data = sorted(data)
data

[-4.826030323435153,
 -4.489086645560824,
 -4.324909606387495,
 -3.4043160474897536,
 -3.3602869782786353,
 -3.31660554276881,
 -3.1641509803215757,
 -2.818986920777156,
 -2.459762915594336,
 -2.305062222274645,
 -2.177433321471092,
 -2.103930223497448,
 -2.01014240982872,
 -1.8287517836148588,
 -1.7864857981539732,
 -1.703834078830385,
 -1.6875368403795183,
 -1.66609434638398,
 -1.5282368879836044,
 -1.5147421276870707,
 -1.4933978544841853,
 -1.4633962575981927,
 -1.069591999763185,
 -1.0096021300369076,
 -0.90300683691585,
 -0.8429573382470683,
 -0.7916801887195111,
 -0.7763532516699163,
 -0.5956153572717687,
 -0.5297174007913097,
 -0.5164342802411568,
 -0.44246297119266814,
 -0.2917961030057393,
 -0.13634218258788347,
 -0.08424837192108968,
 -0.08300593925042789,
 -0.017874984326659706,
 0.01539425178935909,
 0.05460812496207728,
 0.061145967468398996,
 0.0635530972968718,
 0.10134070588661698,
 0.16800280471992535,
 0.17237615403605822,
 0.18417915420538516,
 0.26950953465414296,


In [15]:
tanh_data = [tanh(x) for x in sorted(data)]
tanh_data

[-0.9998714223758713,
 -0.9997477657239985,
 -0.999649744326829,
 -0.9977940312133489,
 -0.9975912128019296,
 -0.9973715973392362,
 -0.9964362369328404,
 -0.9929051095809888,
 -0.9855006971277918,
 -0.9802949171314952,
 -0.9746374557254218,
 -0.9706798955380636,
 -0.9647371871367121,
 -0.9497038172677398,
 -0.945388452221167,
 -0.9358866531441432,
 -0.9338327573464176,
 -0.9310334295109062,
 -0.9101223929527444,
 -0.907776986246746,
 -0.903948047219133,
 -0.8983102113144883,
 -0.7893074569467609,
 -0.7655974056928816,
 -0.7177588003546626,
 -0.6873722884976582,
 -0.6593598060484306,
 -0.6506085826243275,
 -0.5339222085656488,
 -0.4851650406721605,
 -0.4749432960834285,
 -0.4156839128360886,
 -0.28378710671627844,
 -0.13550358727970246,
 -0.08404961050935575,
 -0.08281582659755488,
 -0.017873080794351154,
 0.015393035846025607,
 0.054553908294409745,
 0.06106987648383891,
 0.06346767173530558,
 0.10099520418502235,
 0.16643982519230963,
 0.17068890305247789,
 0.18212445676931574,
 0.263

In [16]:
df = pd.DataFrame({'data': data, 'tanh_data': tanh_data})
df.head()

data  tanh_data
0 -4.826030  -0.999871
1 -4.489087  -0.999748
2 -4.324910  -0.999650
3 -3.404316  -0.997794
4 -3.360287  -0.997591

In [17]:
px.line(df, x='data', y='tanh_data', width=700, height=400, title='Tanh Function')

#### <a name='a5'></a> 1.5 Softmax Function

####   $$S(x_i)=\frac{e^{x_{i}}}{\sum_{j=1}^{N}e^{x_j}},\ \ dla\ i = 1,...,N$$

####   $$S(x_1)=\frac{e^{x_{1}}}{\sum_{j=1}^{N}e^{x_j}}$$

Jest ona przydatna w przypadku problemu klasyfikacji wieloklasowej. 

In [18]:
def softmax(x):
    e_x = np.exp(x)
    denominator = np.sum(e_x, axis=1)
    denominator = denominator[:, np.newaxis]
    return e_x / denominator

In [19]:
data = np.random.randn(4, 5)
data

array([[-1.544826,  0.235543,  1.278456, -1.279924, -0.248838],
       [ 1.174866,  0.016594,  0.459064,  0.645711, -1.44544 ],
       [-0.438272, -1.201953,  0.080526,  0.854507, -0.285091],
       [-1.536362,  1.444288, -1.244652, -0.549834, -1.794019]])

In [20]:
result = softmax(data)
result

array([[0.034817, 0.206533, 0.586033, 0.045377, 0.127241],
       [0.405727, 0.12741 , 0.198319, 0.239015, 0.029529],
       [0.125717, 0.058578, 0.211205, 0.457973, 0.146527],
       [0.039225, 0.772752, 0.052511, 0.105197, 0.030315]])

In [21]:
result.sum(axis=1)

array([1., 1., 1., 1.])